### ISSUE TITLE
Just a heads up (0.93)

### ISSUE THREAD

**Issue by rnateh** [KaiKikuchi/BetterKits#3]
Got this error when someone tried to get the kit twice. (It has a 30m cooldown on it)
http://image.prntscr.com/image/470a2d8ad91a4c64a90cc8d59f82e5ec.png

**Comment by KaiKikuchi** [comment]
Hey thank you for your report! I'll make sure to fix this ASAP.

I suggest to add your server logs too so that will make it easier to fix! Thank you!

**Comment by KaiKikuchi** [comment]
Fixed in v.0.9.4
