### ISSUE TITLE
Issues with Sponge 

### ISSUE THREAD

**Issue by TheBolly** [KaiKikuchi/BetterKits#7]
Hey

I've been trying to use your BetterKits plugin on my Sponge 1.12.2 server but have been receiving this error when trying to /kit (item). Soon I'm also going to be trying on 1.10.2 and 1.7.10 using the same plugin.

It allows me to create a kit. But not get or give it in anyway.

If you could help me out with the error I'm getting here in this log that would be awesome!

[2017-12-29-4.log](https://github.com/KaiKikuchi/BetterKits/files/1593745/2017-12-29-4.log)

Hope you can check this out

Bolly

**Comment by TheBolly** [comment]
Sorry but any idea when this can be looked into. Currently have a lot of plans for my server and can't go forward without solving this issue at the moment.

Happy New Year,

Bolly

**Comment by TheBolly** [comment]
@KaiKikuchi Sorry again for tagging. Really need this looked into. Thanks.

**Comment by KaiKikuchi** [comment]
Please post the fml log.

**Comment by TheBolly** [comment]
Not an issue, sorry for being very persistent to have it looked at.

Anyway, here is my FML log.

[fml-server-latest.log](https://github.com/KaiKikuchi/BetterKits/files/1609825/fml-server-latest.log)

**Comment by KaiKikuchi** [comment]
Try this please: https://github.com/KaiKikuchi/BetterKits/releases/tag/v.0.9.8SpongeAPI7

**Comment by TheBolly** [comment]
That worked perfectly! Thank you for fixing this as it will help us massively
